### ISSUE TITLE
Really Long Repo Comments Break

### ISSUE THREAD

**Issue by PlushyObject** [deepthought42/ideaBin#135]
Added a really long lorem ipsum comment and it broke the comment.  didnt display the date or the comment

**Comment by deepthought42** [comment]
This is because of database field length restrictions. Validation will need to be added. We've decided 250 characters is a good length. Assigning to me so that I can handle the validation.

**Comment by deepthought42** [comment]
Length validation added. Working on requirement for it to be non empty to show error message

**Comment by deepthought42** [comment]
Done
