### ISSUE TITLE
change menu to sidebar

### ISSUE THREAD

**Issue by deepthought42** [deepthought42/ideaBin#19]
Currently the menu is a header, and we want to change it so that it is a sidebar menu on the left side of the window

**Comment by PlushyObject** [comment]
hell ya haha




Regards,
James Darrohn
Graphic & Web Designer
Cell: 727.470.4399
jamesdarrohn@gmail.com
*Darrohn Design*

**Comment by deepthought42** [comment]
This was closed as a duplicate. See issue #21 for newer one
