### ISSUE TITLE
Make ideas use css3 card flip

### ISSUE THREAD

**Issue by deepthought42** [deepthought42/ideaBin#52]
When a user hovers over ideas on the index page currently the idea name and description is shown over the cover image. change this so that the card flips and shows the name and description on the back

**Comment by deepthought42** [comment]
cards are flipping but css was altered in such a way that previous layout was broken. Images no longer line up evenly and seemlessly. This should be fixed.

**Comment by PlushyObject** [comment]
Dizzone
