### ISSUE TITLE
turn buttons in navigation bar into icons

### ISSUE THREAD

**Issue by deepthought42** [deepthought42/ideaBin#69]
Buttons should be icons in navigation bar

**Comment by PlushyObject** [comment]
Is this referring to All Ideas, My Ideas?

**Comment by deepthought42** [comment]
Ya. I'm not digging the text buttons. I think they'd be better as icons that show their intent when you mouse over in a tooltip

**Comment by deepthought42** [comment]
I really like the toolbar style that this site has and would like to emulate this. 

http://www.codingame.com/

**Comment by deepthought42** [comment]
tool bar looks good. Closing this out.
